# Hot Reload Configuration for Tchat Backend Microservices
# Optimized for Go 1.22+ development with multiple services

root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ./backend/services/auth-service/main.go"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "frontend", "apps", "specs"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = ["backend"]
  include_ext = ["go", "tpl", "tmpl", "html", "yaml", "yml"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_root = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false

# Service-specific profiles for individual microservice development
[service.auth]
  cmd = "go build -o ./tmp/auth-service ./backend/services/auth-service/main.go"
  bin = "./tmp/auth-service"
  
[service.messaging]  
  cmd = "go build -o ./tmp/messaging-service ./backend/services/messaging-service/main.go"
  bin = "./tmp/messaging-service"

[service.payment]
  cmd = "go build -o ./tmp/payment-service ./backend/services/payment-service/main.go"
  bin = "./tmp/payment-service"

[service.commerce]
  cmd = "go build -o ./tmp/commerce-service ./backend/services/commerce-service/main.go"
  bin = "./tmp/commerce-service"

[service.notification]
  cmd = "go build -o ./tmp/notification-service ./backend/services/notification-service/main.go"
  bin = "./tmp/notification-service"