# SwiftLint Configuration for Tchat iOS App
# Ensures code quality and consistency across the iOS codebase

# Paths to include in linting
included:
  - Sources
  - Tests

# Paths to exclude from linting
excluded:
  - Pods
  - DerivedData
  - .build

# Disabled rules
disabled_rules:
  - trailing_whitespace # Handled by editor
  - todo # Allow TODO comments for development

# Opt-in rules to enable
opt_in_rules:
  - array_init
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - force_unwrapping
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

type_body_length:
  warning: 300
  error: 400

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 6
  error: 8

cyclomatic_complexity:
  warning: 10
  error: 20

file_length:
  warning: 400
  error: 500

type_name:
  min_length: 3
  max_length: 40

identifier_name:
  min_length: 3
  max_length: 40
  excluded:
    - id
    - x
    - y
    - z

large_tuple:
  warning: 3
  error: 4

# Custom rules
custom_rules:
  # Encourage using self consistently
  explicit_self:
    name: "Explicit Self"
    regex: '(?<!self\.)\b(backgroundColor|textColor|font|frame|bounds|center|alpha|transform|isHidden|isUserInteractionEnabled)\b'
    message: "Use explicit self for UI properties"
    severity: warning

  # Discourage force unwrapping in production code
  no_force_unwrapping:
    name: "No Force Unwrapping"
    regex: '\!\s*$'
    match_kinds:
      - identifier
    message: "Avoid force unwrapping - use safe unwrapping instead"
    severity: warning

# File header template
file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*\.swift
                    \/\/  TchatApp
                    \/\/
                    \/\/  Created by .* on \d{1,2}\/\d{1,2}\/\d{4}\.
                    \/\/

# Reporter type
reporter: "xcode"