global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # API Gateway
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: /metrics
    scrape_interval: 10s

  # Auth Service
  - job_name: 'auth-service'
    static_configs:
      - targets: ['host.docker.internal:8081']
    metrics_path: /metrics
    scrape_interval: 10s

  # Messaging Service
  - job_name: 'messaging-service'
    static_configs:
      - targets: ['host.docker.internal:8082']
    metrics_path: /metrics
    scrape_interval: 10s

  # Commerce Service
  - job_name: 'commerce-service'
    static_configs:
      - targets: ['host.docker.internal:8084']
    metrics_path: /metrics
    scrape_interval: 10s

  # Content Service
  - job_name: 'content-service'
    static_configs:
      - targets: ['host.docker.internal:8086']
    metrics_path: /metrics
    scrape_interval: 10s

  # Infrastructure Services
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Node Exporter (if running)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']
    scrape_interval: 30s