[build]
builder = "dockerfile"
dockerfilePath = "auth/Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[[services]]
name = "auth-service"
source = "."

[services.healthcheck]
path = "/health"
timeout = 30

[services.variables]
APP_ENVIRONMENT = "production"
ENVIRONMENT = "production"
LOG_LEVEL = "info"
SERVICE_NAME = "auth-service"
SERVICE_PORT = "8081"
AUTH_SERVICE_PORT = "8081"
DATABASE_NAME = "auth_service_db"
DB_DATABASE = "auth_service_db"
DB_NAME = "auth_service_db"
DB_SCHEMA = "public"
REDIS_NAMESPACE = "auth-service"
JWT_ISSUER = "https://auth.tchat.app"
JWT_AUDIENCE = "tchat-users"
METRICS_ENABLED = "true"
HEALTHCHECK_PATH = "/health"
