[build]
builder = "dockerfile"
dockerfilePath = "infrastructure/gateway/Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[[services]]
name = "gateway-service"
source = "."

[services.healthcheck]
path = "/health"
timeout = 30

[services.variables]
APP_ENVIRONMENT = "production"
ENVIRONMENT = "production"
LOG_LEVEL = "info"
SERVICE_NAME = "gateway-service"
SERVICE_PORT = "8080"
GATEWAY_SERVICE_PORT = "8080"
AUTH_SERVICE_URL = ""
MESSAGING_SERVICE_URL = ""
PAYMENT_SERVICE_URL = ""
COMMERCE_SERVICE_URL = ""
NOTIFICATION_SERVICE_URL = ""
CONTENT_SERVICE_URL = ""
VIDEO_SERVICE_URL = ""
METRICS_ENABLED = "true"
HEALTHCHECK_PATH = "/health"
