[build]
builder = "dockerfile"
dockerfilePath = "video/Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[[services]]
name = "video-service"
source = "."

[services.healthcheck]
path = "/health"
timeout = 30

[services.variables]
APP_ENVIRONMENT = "production"
ENVIRONMENT = "production"
LOG_LEVEL = "info"
SERVICE_NAME = "video-service"
SERVICE_PORT = "8091"
VIDEO_SERVICE_PORT = "8091"
DATABASE_NAME = "video_service_db"
DB_DATABASE = "video_service_db"
DB_NAME = "video_service_db"
DB_SCHEMA = "public"
REDIS_NAMESPACE = "video-service"
MEDIA_CDN_BASE_URL = ""
METRICS_ENABLED = "true"
HEALTHCHECK_PATH = "/health"
